### ISSUE TITLE
MP test driver (CONFIG_MP_INCLUDED = y)

### ISSUE THREAD

**Issue by blpanadero** [lwfinger/rtl8723bu#83]
Has anyone compiled rtl8723bu driver with CONFIG_MP_INCLUDED option enabled? 

Why this option is only available in the Makefile which are into the .tar file? 

When I make this file with CONFIG_MP_INCLUDED=y appears a lot of errors on several files. I need compile the driver with this option enabled to test the bluetooth and wifi on LM811 module.

**Comment by lwfinger** [comment]
That MP code was stripped out. If you want that "feature", you will need to start with Realtek's tarball.

**Comment by blpanadero** [comment]
I have the rtl8723bu and rtl8723au_bt compiled on my target and I trying recompiling it with this option enabled. How I can start with Realtek's tarball? What I have to do?

Regards.

**Comment by lwfinger** [comment]
You will need to find the driver on some website, download it, unpack the tar file, and build it. You will also need to handle any missing updates for kernel API changes.

The MP "feature" is for the manufacturing process. With it enabled, there is a lot of overhead and log spamming, which is why I disabled it.

**Comment by blpanadero** [comment]
Hi again,

I have searching the driver on a lot of websites, but I could not find it. Could you say me where did you get it?  

Thanks and regards.
